### ISSUE TITLE
How to use atlan-java SNAPSHOT version 

### ISSUE THREAD

**Issue by aeiou-st** [atlanhq/atlan-java#122]
Hello , I want to know if there is any way to use snapshots version on my android project not actual release version.

**Comment by cmgrote** [comment]
Hi @aeiou-st — I’m not super familiar with Android projects, but I would imagine as long as you can declare the repositories for dependencies this should be possible.

For an example using Gradle, see: https://github.com/atlanhq/atlan-java-samples/blob/d6415cc8375e1a4cc765eb6d709985c0828d15f4/build.gradle#L73

**Comment by aeiou-st** [comment]
@cmgrote Thank you so much for example it  worked for me.
>be aware that the snapshot versions may change frequently before release, 

yes i'll be take care of version.

**Comment by aeiou-st** [comment]
Hello @cmgrote ,I know this type question belongs to stackoverflow but can you help me with this issue because i'm new to SDK development and i already did Research about this issue for 3 days but there is nothing any important i get.

As you helped me with Snapshot version thank you once again.
>In SDK we use iso parser library for video compression and some more. It works fine in testing project but when i implement snapshot version to other project iso parser not work as it should be means while video compression it drops the audio i don't why but when i code write this all works fine 

`implementation ('com.name.lib:Library:1.2.19-SNAPSHOT'){
        exclude group: 'com.googlecode.mp4parser', module: 'isoparser'
    }
    implementation ('com.googlecode.mp4parser:isoparser:1.0.6'){
        force = true
    }`

**Comment by aeiou-st** [comment]
Thank you
