### ISSUE TITLE
Weird result when creating tables

### ISSUE THREAD

**Issue by archenroot** [atlanhq/atlan-java#395]
I created set of 10 tables using following code:
```
            String connectionQn = "commercial_it/metadata/DEV_dce2_adl_new";
            String databaseQn = connectionQn + "/DEV_DCE2_ADL";
            String schemaQn = databaseQn + "/DEV_ADL";
            String tableNamePrefix = "benchmarkTable";
            int tableCount = 10;
            
            for (int i = 1; i <= tableCount; ++i) {
                Table table = Table.creator(tableNamePrefix + "-" + Integer.toString(i), schemaQn)
                        .tableQualifiedName(schemaQn + "/" + tableNamePrefix + "-" + Integer.toString(i))
                        .build();
                AssetMutationResponse tableSaveResponse = client.assets.save(table);
                String toJson = tableSaveResponse.toJson(client);
                log(toJson);
//                String assignedGuid = tableSaveResponse.getAssignedGuid(table);
//                AssetDeletionResponse deleteResponse = client.assets.delete(assignedGuid, AtlanDeleteType.DEFAULT);
//                toJson = deleteResponse.toJson(client);
//                log(toJson);
            }

......
 public static void log(String ao){
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        JsonElement jsonElement = JsonParser.parseString(ao);
        String prettyJsonString = gson.toJson(jsonElement);
        logger.log(Level.INFO, prettyJsonString);
    }
```
The issue is that when I cannot see the tables in the search view:
![image](https://github.com/atlanhq/atlan-java/assets/553512/9a23f838-7ae4-46a4-8c26-92b98b9e8554)
Note just single table in the search asset view. I created my tables under schema DEV_ADL. When I click on Tables, there is just one:
![image](https://github.com/atlanhq/atlan-java/assets/553512/70ae0c75-c4e6-40a8-b9aa-82e5f247bb6e)

But when I access the schema itself and display linked artifacts, the tables are shown. I think I miss use the api somehow.
![image](https://github.com/atlanhq/atlan-java/assets/553512/6d040e57-6597-4f94-91fd-b6ea51ef2edb)

That is weird....

**Comment by archenroot** [comment]
While running following code:
```
       String connectionQn = "commercial_it/metadata/DEV_dce2_adl_new";
            String databaseQn = connectionQn + "/DEV_DCE2_ADL";
            String schemaQn = databaseQn + "/DEV_ADL";
            String tableNamePrefix = "benchmarkTable";
            int tableCount = 100;
            String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());
            Instant start = Instant.now();
            logString("START - " + timeStamp);
            AtlanClient client = Atlan.getDefaultClient();
            client.setMaxNetworkRetries(10);
            sequencialTableCreation(client, tableCount, connectionQn, databaseQn, schemaQn, tableNamePrefix);
//            parallelTableCreation(tableCount, tableNamePrefix, schemaQn);
            logString("END - " + timeStamp);
            Instant end = Instant.now();
            Duration duration = Duration.between(start, end);
            logString("Duration - " + duration.toString());
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }
    public static void sequencialTableCreation(AtlanClient client, int tableCount, String connectionQn, String databaseQn, String schemaQn, String tableNamePrefix) throws InterruptedException{
        for (int i = 1; i <= tableCount; ++i) {
            final int threadId = i;
                try {
                    
                    logString("Thread-" + Integer.toString(threadId) + " started - " + new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date()));
                    String tableName = tableNamePrefix + "-" + Integer.toString(threadId);
                    String tableQn = schemaQn + "/" + tableName;
                    Table table = Table.creator(tableName, schemaQn)
                        .tableQualifiedName(tableQn)
                        .connectionQualifiedName(connectionQn)
                        .databaseQualifiedName(tableName)
                        .build();
                    // , RequestOptions.from(client).build()
                    AssetMutationResponse tableSaveResponse = client.assets.save(table);
                    String toJson = tableSaveResponse.toJson(client);
                    //logString(toJson);
                    log(toJson);
                    String assignedGuid = tableSaveResponse.getAssignedGuid(table);
                    logString("assignedGui: " + assignedGuid);
                    Thread.sleep(Duration.ofSeconds(Long.valueOf("1")));
                    AssetDeletionResponse deleteResponse = client.assets.delete(assignedGuid, AtlanDeleteType.HARD);
                    String deleteResponseJson = deleteResponse.toJson(client);
                    logString("Delete response: " + deleteResponseJson);
                    logString("Thread-" + Integer.toString(threadId) + " finished - " + new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date()));
                } catch (AtlanException ex) {
                    Logger.getLogger(AtlanApiBenchmark.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
                
    }
```

I am getting deletion error and tables not seen in UI at all, here is sample log for 1 iteration:
```
Dec 23, 2023 6:46:25 PM net.pmi.atlan.api.benchmark.AtlanApiBenchmark log
INFO: {
  "guidAssignments": {
    "-1394208664968604887": "7ae472e2-af86-4fda-9013-b86ff1918071"
  }
}
Dec 23, 2023 6:46:25 PM net.pmi.atlan.api.benchmark.AtlanApiBenchmark logString
INFO: assignedGui: 7ae472e2-af86-4fda-9013-b86ff1918071
Dec 23, 2023 6:46:26 PM net.pmi.atlan.api.benchmark.AtlanApiBenchmark logString
INFO: Delete response: {}
```
On upsert I get guidAssignment, but when I try to delete i get empty deletion response...hm

**Comment by cmgrote** [comment]
> I created set of 10 tables using following code:
> 
> ```
>             String connectionQn = "commercial_it/metadata/DEV_dce2_adl_new";
>             String databaseQn = connectionQn + "/DEV_DCE2_ADL";
>             String schemaQn = databaseQn + "/DEV_ADL";
>             String tableNamePrefix = "benchmarkTable";
>             int tableCount = 10;
>             
>             for (int i = 1; i <= tableCount; ++i) {
>                 Table table = Table.creator(tableNamePrefix + "-" + Integer.toString(i), schemaQn)
>                         .tableQualifiedName(schemaQn + "/" + tableNamePrefix + "-" + Integer.toString(i))
>                         .build();
>                 AssetMutationResponse tableSaveResponse = client.assets.save(table);
>                 String toJson = tableSaveResponse.toJson(client);
>                 log(toJson);
> //                String assignedGuid = tableSaveResponse.getAssignedGuid(table);
> //                AssetDeletionResponse deleteResponse = client.assets.delete(assignedGuid, AtlanDeleteType.DEFAULT);
> //                toJson = deleteResponse.toJson(client);
> //                log(toJson);
>             }

The connection qualifiedName you've hand-coded as a string is not going to match the connection shown in the screenshots. All connection qualifiedNames are generated, and have the form `default/<type>/<epoch>` — in this case it will be something like `default/mysql/1234567890`.

The UI is largely driven by adherence to these qualifiedNames all the way down the hierarchy of assets within a connection, so it's the non-adherence to this qualifiedName structure that's causing inconsistencies in the UI.

A step-by-step example going from connection down through all the subtypes of relational assets is documented here: https://developer.atlan.com/patterns/create/relational/ — note that each step down the relational hierarchy (connection -> database -> schema -> ...) reuses the parent object, to ensure this qualifiedName is consistently built-up for each child object.

Alternatively, now that your connection already exists, you can use a snippet like the following to retrieve a connection based on its name and type (and from the result you can get its generated qualifiedName): https://developer.atlan.com/snippets/common-examples/finding/connection/#find-all-connections

**Comment by archenroot** [comment]
@cmgrote - thank you for your feedback, I think my weird output is due to some misusing of SDK. I am closing this.
